# Basic
name: Ian Lee
author: Ian Lee
author_email: IanLee1521@gmail.com
title: Ian Lee
url: "http://ianlee1521.com"

# Images
logo: assets/img/headshot.png

exclude:
  - CNAME
  - README.md

google_analytics:
  tracking_id: UA-72759126-1

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: ianlee1521/ianlee1521.github.io
gems: ['jekyll-github-metadata']

social:
  name: Ian Lee
  handle: IanLee1521

# Build Config
highlighter: pygments
markdown: kramdown
timezone: America/Los_Angeles
encodign: UTF-8
branch: master
