# Site settings
locale: en-US
title: Ian Lee
description: "I'm Ian Lee, a cyber security professional and open source evangelist."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ianlee1521.com"
repository: IanLee1521/IanLee1521.github.io
comments:
    provider: "disqus"
    disqus:
        shortname: IanLee1521

# Account
author:
    name             : Ian Lee
    avatar           : https://s.gravatar.com/avatar/c416a04a16b233e65afd993815c167dd?s=256
    bio              : "Leave things better than you found them."  # "Explorer, Collaborator, and Open Source Evangelist."
    location         : "Livermore, CA, USA"
    email            : IanLee1521@gmail.com
    uri              : https://ianlee1521.com
    home             : https://ianlee1521.com
    bitbucket        : IanLee1521
    codepen          :
    dribbble         :
    flickr           :
    facebook         :
    foursquare       :
    github           : IanLee1521
    gitlab           : IanLee1521
    google_plus      : +IanLee1521
    keybase          :
    instagram        :
    lastfm           :
    linkedin         : IanLee1521
    pinterest        :
    soundcloud       :
    stackoverflow    : "450858/ian-lee"
    steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
    tumblr           :
    twitter          : IanLee1521
    vine             :
    weibo            :
    xing             :
    youtube          : "https://youtube.com/c/IanLee1521"

twitter:
    username: "IanLee1521"
og_image: https://s.gravatar.com/avatar/c416a04a16b233e65afd993815c167dd?s=256

footer:
    links:
        - label: "Twitter"
          icon: "fab fa-fw fa-twitter-square"
          url: "https://twitter.com/IanLee1521"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/IanLee1521"

# Analytics
analytics:
    provider: "google-gtag"
    google:
        tracking_id: UA-72759126-1

# Build settings
plugins:
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-include-cache
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
# minimal_mistakes_skin: "neon"
# minimal_mistakes_skin: "dirt"
minimal_mistakes_skin: "air"
paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
    - "_pages"

permalink: /:categories/:year/:month/:day/:title/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
